name: rl-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - sympy
  - networkx
  - jinja2
  - markupsafe
  - packaging
  - pillow
  - python-dateutil
  - pytz
  - filelock
  - typing_extensions
  - fsspec
  - six
  - mpmath
  - fonttools
  - kiwisolver
  - contourpy
  - cycler
  - werkzeug
  - grpcio
  - absl-py
  - pip:
      - Farama-Notifications==0.0.4
      - gymnasium==1.0.0
      - sb3_contrib==2.6.0
      - stable-baselines3==2.6.0
      - torch==2.6.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - protobuf==6.30.1
      - markdown==3.7
      - fastapi[all]
      - pygame==2.6.1
